-- 적용 완료: 2026-10-03 (임박사 승인). 테이블 public.kbpi_events
-- brainmind_events 대신 사이트 전체 기록용 kbpi_events 하나로 통합했습니다.
-- 권한: 익명 방문자는 기록 추가(insert)만 가능, 조회·수정·삭제 불가. 관리자는 Supabase 대시보드/SQL에서 조회.
-- 롤백: drop table public.kbpi_events;
-- 조회 예시(대시보드 SQL): select event, count(*) from public.kbpi_events group by 1;
